### PR TITLE
Typescript compatibility

### PR DESCRIPTION
**Pull request by theoparis**
Added autogenerated typescript types from the js files

### CODE REVIEW

**Comment by Irrelon** [comment]
Hey, thanks for the PR!

Just a quick one, any chance you could add into the scripts section of package.json the generator functionality so that when changes are made the def file is kept automatically up to date with the JSDoc?

**Comment by theoparis** [comment]
So you want me just to seperate the typescript command into a seperate script in the package.json?

**Comment by Irrelon** [comment]
Is it just the tsc command that generates the def files from the jsdoc?

**Comment by theoparis** [comment]
> Is it just the tsc command that generates the def files from the jsdoc?

Yes - `tsc` does it using the tsconfig.json file that I added.

**Comment by Irrelon** [comment]
Ahh apologies! I figured there was more to it! Thanks for clarifying.

**Comment by Irrelon** [comment]
I’ll get a new version published to npm shortly

**Pull request merged**
